// AUTO-GENERATED by build-projects.py — do not edit directly.
// Source: projects/posts/*.md
// Last built: 2026-04-24
//
// To add or edit a project:
//   1. Edit (or create) a .md file in projects/posts/
//   2. Run: python build-projects.py
//   3. Reload your browser

window.PROJECTS_DATA = [
  {
    "id": "intune-modernisering",
    "slug": "intune-modernisering",
    "title": "Intune — modernisering av maskinparkadministrasjon",
    "role": "IT-koordinator / Prosjektleder",
    "period": "Vinter 2025",
    "year": 2025,
    "featured": true,
    "status": "delivered",
    "sort": 10,
    "tags": ["Intune", "Microsoft 365", "Entra ID"],
    "keywords": ["intune", "GPO", "gruppepolicy", "endepunktsadministrasjon", "maskinpark", "sky", "azure", "entra id", "microsoft 365", "MDM", "modernisering"],
    "excerpt": "Reaktiverte et fryst prosjekt og moderniserte administrasjonen av organisasjonens maskinpark — fra tradisjonelle gruppepolicyer til Microsoft Intune, som del av en fullstendig skymigrering.",
    "contentHtml": "<p>I vinteren 2025 tok jeg initiativ til å reaktivere et prosjekt som hadde ligget fryst i lang tid. Målet var å modernisere administrasjonen av organisasjonens maskinpark ved å gå fra tradisjonelle gruppepolicyer (GPO) til Microsoft Intune.</p>\n<p>Prosjektet henger tett sammen med en bredere skymigrering — foreningen hadde allerede kuttet lokal filserver fullstendig og gått over til skybasert lagring.</p>\n<p><strong>Tilnærming:</strong></p>\n<ul><li>Gjennomgikk eksisterende GPO-struktur og identifiserte hvilke policyer som skulle migreres eller erstattes</li><li>Konfigurerte Intune-miljøet og satte opp policyer for enhetsstyring</li><li>Koordinerte utrulling uten å forstyrre den daglige driften</li><li>Dokumenterte den nye prosessen for innrulling av nye maskiner</li></ul>\n<p><strong>Resultater:</strong></p>\n<ul><li>Bedre endepunktsadministrasjon med sentralisert oversikt i Intune</li><li>Betydelig lavere tidsbruk og kostnad ved innrulling av nye maskiner</li><li>Fullstendig overgang til skybasert infrastruktur</li><li>Prosjektet ferdigstilt etter lang periode uten fremdrift</li></ul>"
  },
  {
    "id": "saksbehandlingssystem-sharepoint",
    "slug": "saksbehandlingssystem-sharepoint",
    "title": "Saksbehandlingssystem i SharePoint",
    "role": "IT-konsulent / Utvikler",
    "period": "Sommer 2025",
    "year": 2025,
    "featured": true,
    "status": "delivered",
    "sort": 15,
    "tags": ["SharePoint", "Microsoft Lists", "Microsoft 365"],
    "keywords": ["sharepoint", "microsoft lists", "saksbehandling", "excel", "modernisering", "microsoft 365", "workflow", "løsning", "lavterskel"],
    "excerpt": "Utviklet et saksbehandlingssystem i SharePoint som erstattet utdaterte Excel-lister — en lavterskelløsning som ble tatt i bruk umiddelbart og svært godt mottatt i avdelingen.",
    "contentHtml": "<p>Sommeren 2025 utviklet jeg et saksbehandlingssystem i SharePoint for å forenkle håndteringen av saker på ukentlige møter i avdelingen.</p>\n<p>Løsningen erstattet et sett med utdaterte Excel-lister som hadde blitt vanskelige å vedlikeholde og lite egnet for samarbeid. Målet var noe moderne, men enkelt nok til at alle i avdelingen kunne bruke det uten opplæring.</p>\n<p><strong>Tilnærming:</strong></p>\n<ul><li>Kartla eksisterende arbeidsflyt og smertepunkter med Excel-løsningen</li><li>Designet en struktur i Microsoft Lists tilpasset saksgangen i ukemøtene</li><li>Konfigurerte visninger, statuser og filtrering for ulike bruksscenarioer</li><li>Gjennomførte innføring og sikret at teamet var komfortabelt med løsningen fra dag én</li></ul>\n<p><strong>Resultater:</strong></p>\n<ul><li>Erstattede fragmenterte Excel-lister med én samlet, søkbar løsning</li><li>Saksbehandlingen i ukemøtene ble merkbart mer effektiv</li><li>Svært godt mottatt i avdelingen — tatt i bruk umiddelbart</li><li>Lavterskel nok til at alle brukte det uten formell opplæring</li></ul>"
  },
  {
    "id": "arbeidsflyter-sanntidsmarketing",
    "slug": "arbeidsflyter-sanntidsmarketing",
    "title": "Arbeidsflyter — sanntidsmarkedsføring",
    "role": "IT-konsulent / Intern kursleder",
    "period": "2024",
    "year": 2024,
    "featured": true,
    "status": "delivered",
    "sort": 20,
    "tags": ["Power Automate", "Microsoft 365", "Opplæring"],
    "keywords": ["power automate", "real-time marketing", "dynamics", "marketing", "opplæring", "arbeidsflyter", "automatisering", "microsoft 365"],
    "excerpt": "Da Microsoft besluttet å avvikle utgående markedsføring til fordel for sanntidsmarkedsføring, fikk jeg ansvar for intern opplæring av nøkkelpersoner — med mål om at foreningen skulle eie løsningene selv.",
    "contentHtml": "<p>Da Microsoft i 2024 besluttet å avvikle utgående markedsføring til fordel for sanntidsmarkedsføring, fikk jeg ansvar for intern opplæring av nøkkelpersoner i organisasjonen.</p>\n<p>Målet var å være i forkant av en kritisk plattformendring — og å sikre at foreningen på sikt kunne forvalte, tilpasse og videreutvikle løsningene selv, uten å være avhengig av ekstern bistand for hver justering.</p>\n<p><strong>Tilnærming:</strong></p>\n<ul><li>Kartla hvilke arbeidsflyter og kampanjer som ville bli berørt av overgangen</li><li>Utarbeidet intern opplæringsplan tilpasset ulike brukernivåer</li><li>Gjennomførte praktisk opplæring av nøkkelpersoner i det nye grensesnittet</li><li>Dokumenterte prosesser og løsninger for fremtidig vedlikehold</li></ul>\n<p><strong>Resultater:</strong></p>\n<ul><li>Organisasjonen var forberedt før den kritiske overgangsfristen</li><li>Nøkkelpersoner ble selvstendige i sanntidsmarkedsføring</li><li>Redusert avhengighet av ekstern hjelp for løpende tilpasninger</li></ul>"
  },
  {
    "id": "power-apps-power-bi-mal",
    "slug": "power-apps-power-bi-mal",
    "title": "Power Apps / Power BI — KPI-applikasjon",
    "role": "Selvstendig prosjekt",
    "period": "Høst 2024",
    "year": 2024,
    "featured": true,
    "status": "delivered",
    "sort": 25,
    "tags": ["Power Apps", "Power BI", "Microsoft 365"],
    "keywords": ["power apps", "power bi", "KPI", "dashboard", "rapportering", "canvas app", "mal", "avdeling", "organisasjon", "microsoft 365"],
    "excerpt": "Bygget en mal-applikasjon i Power Apps med integrerte Power BI-rapporter — separate sider per avdeling og en overordnet side for ledernivå.",
    "contentHtml": "<p>Høsten 2024 brukte jeg en god del fritid på å sette meg grundig inn i Power Platform — med særlig fokus på Power Apps for økt kompleksitet utover enkle flyter.</p>\n<p>Resultatet ble en mal-applikasjon der man kan plugge inn KPI-data eller koble til Power BI-rapporter, med separate sider per avdeling og en overordnet side for hele organisasjonen.</p>\n<p><strong>Tilnærming:</strong></p>\n<ul><li>Satte meg inn i canvas-arkitektur og datakildeintegrasjon i Power Apps</li><li>Designet en fleksibel mal som kan tilpasses ulike organisasjoners struktur</li><li>Integrerte Power BI-rapporter direkte i applikasjonen</li><li>Bygget separate visninger per avdeling med en felles landingsside for ledernivå</li></ul>\n<p><strong>Resultater:</strong></p>\n<ul><li>En gjenbrukbar mal for KPI- og rapportvisualisering i Power Apps</li><li>Økt forståelse for Power Apps som utviklingsverktøy utover enkle skjemaer</li><li>Grunnlag for videre prosjekter og mer avansert bruk av Power Platform</li></ul>"
  }
];
