// AUTO-GENERATED by build-projects.py - do not edit directly.
// Source: projects/posts/*.md
// Last built: 2026-05-07 18:49
//
// To add or edit a project:
//   1. Edit (or create) a .md file in projects/posts/
//   2. Run: python build-projects.py
//   3. Reload your browser
//
// Files starting with _ (e.g. _template.md) are excluded from the build.

window.PROJECTS_DATA = [
  {
    "id": "modulart-ticketsystem",
    "slug": "modular-ticket-and-case-management-system",
    "title": "Modular ticket and case-management system",
    "role": "IT Consultant / Self-initiated project lead",
    "period": "2025 — ongoing",
    "year": 2025,
    "featured": true,
    "status": "in-progress",
    "sort": 5,
    "tags": [
      "SharePoint",
      "Power Automate",
      "Power Apps",
      "Microsoft 365"
    ],
    "keywords": [
      "sharepoint",
      "power automate",
      "power apps",
      "microsoft forms",
      "ticketing",
      "case management",
      "workflows",
      "automation",
      "modular",
      "microsoft 365",
      "governance",
      "preboarding",
      "offboarding",
      "change request"
    ],
    "excerpt": "In 2025 I designed and built a modular ticket- and case-management system on top of SharePoint lists, Power Automate, and Power Apps/Forms as the frontend. Power Automate helper lists generate the underlying tasks for each incoming case, and the architecture is deliberately built for extension — new processes plug in as new modules.",
    "contentHtml": "<p>In 2025 I designed and built a modular ticket- and case-management system on top of SharePoint lists, Power Automate, and Power Apps/Forms as the frontend. Power Automate helper lists generate the underlying tasks for each incoming case, and the architecture is deliberately built for extension — new processes plug in as new modules.</p>\n<p>This was a self-initiated project, triggered by a gap I uncovered during an internal stand-in: one employee had a firm grip on their own workload, but the processes were invisible to the rest of the organisation. Things ran in personal inboxes and Teams channels, and there was no shared view of what was in flight or what had been promised.</p>\n<p><strong>Approach:</strong></p>\n<ul><li>Mapped the recurring case types that were quietly running through email and Teams, and grouped them into modules</li><li>Built the SharePoint list structure and the Power Automate flows that translate a single submission into the underlying tasks</li><li>Used Power Apps and Forms as low-friction frontends so the system fits the way people already work</li><li>Designed the modules to be added independently, so a new process is a new module rather than a rebuild</li></ul>\n<p><strong>Modules:</strong></p>\n<ul><li><strong>Delivered:</strong> preboarding, change requests</li><li><strong>In development:</strong> licence administration, offboarding, procurement</li></ul>\n<p><strong>Results:</strong></p>\n<ul><li>Replaces personal inboxes and ad-hoc Teams posts with a shared, visible system of record</li><li>Rolling out across the leadership group, the IT department, and departments with external roles that need follow-up</li><li>Built to extend — new modules slot in without disturbing the ones already running</li></ul>"
  },
  {
    "id": "intune-modernisering",
    "slug": "gpo-to-microsoft-intune-migration",
    "title": "GPO to Microsoft Intune migration",
    "role": "IT Consultant / Project Lead",
    "period": "Winter 2025",
    "year": 2025,
    "featured": true,
    "status": "delivered",
    "sort": 10,
    "tags": [
      "Intune",
      "Microsoft 365",
      "Entra ID"
    ],
    "keywords": [
      "intune",
      "GPO",
      "group policy",
      "endpoint management",
      "device fleet",
      "cloud",
      "azure",
      "entra id",
      "microsoft 365",
      "MDM",
      "modernisation",
      "autopilot"
    ],
    "excerpt": "In the winter of 2025 I picked up a project that had been frozen for some time and got it moving again. The goal was to migrate around 80 machines from traditional Group Policy (GPO) to Microsoft Intune — modernising endpoint management and lining up with the broader cloud migration the organisation was already in the middle of.",
    "contentHtml": "<p>In the winter of 2025 I picked up a project that had been frozen for some time and got it moving again. The goal was to migrate around 80 machines from traditional Group Policy (GPO) to Microsoft Intune — modernising endpoint management and lining up with the broader cloud migration the organisation was already in the middle of.</p>\n<p>I drove the work alone from the organisation's side, in collaboration with our managed service provider, and completed the move over roughly two months.</p>\n<p><strong>Approach:</strong></p>\n<ul><li>Reviewed the existing GPO setup and decided which policies to migrate, replace, or retire</li><li>Configured the Intune environment and built out device-management policies</li><li>Coordinated the rollout in phases so it didn't disrupt day-to-day operations</li><li>Documented the new enrollment process so onboarding a device is now a routine task</li></ul>\n<p><strong>Results:</strong></p>\n<ul><li>~80 machines migrated from GPO to Intune over two months</li><li>Centralised endpoint management with a single pane of glass</li><li>New machine enrolment now costs roughly NOK 3,000 less per device, a</li></ul>"
  },
  {
    "id": "saksbehandlingssystem-sharepoint",
    "slug": "case-management-system-for-weekly-department-meetings",
    "title": "Case management system for weekly department meetings",
    "role": "IT Consultant / Developer",
    "period": "Summer 2025",
    "year": 2025,
    "featured": true,
    "status": "delivered",
    "sort": 15,
    "tags": [
      "SharePoint",
      "Microsoft Lists",
      "Power Automate",
      "Microsoft 365"
    ],
    "keywords": [
      "sharepoint",
      "microsoft lists",
      "power automate",
      "case management",
      "excel",
      "modernisation",
      "microsoft 365",
      "workflow",
      "low-code",
      "notifications"
    ],
    "excerpt": "In the summer of 2025 I replaced a tangle of ageing Excel lists with a SharePoint and Microsoft Lists solution covering an entire department of twelve. The brief was for something modern, but simple enough that everyone could use it without training.",
    "contentHtml": "<p>In the summer of 2025 I replaced a tangle of ageing Excel lists with a SharePoint and Microsoft Lists solution covering an entire department of twelve. The brief was for something modern, but simple enough that everyone could use it without training.</p>\n<p>The work later became the foundation for the modular ticket system the IT team now runs across the organisation.</p>\n<p><strong>Approach:</strong></p>\n<ul><li>Mapped the existing workflow and the pain points of the Excel-based setup</li><li>Designed a Microsoft Lists structure tailored to how cases moved through the weekly meetings</li><li>Added automatic metadata, status tracking, and progression through Power Automate</li><li>Wired up automatic notifications to case owners so nothing fell off anyone's plate</li><li>Configured views and filters for the different ways the team needed to slice the data</li><li>Ran the rollout so the team felt comfortable with the new system from day one</li></ul>\n<p><strong>Results:</strong></p>\n<ul><li>Replaced fragmented Excel sheets with a single, searchable system with full hi</li></ul>"
  },
  {
    "id": "arbeidsflyter-sanntidsmarketing",
    "slug": "dynamics-365-real-time-marketing-transition",
    "title": "Dynamics 365 — real-time marketing transition",
    "role": "IT Consultant / Internal Trainer",
    "period": "2024",
    "year": 2024,
    "featured": true,
    "status": "delivered",
    "sort": 20,
    "tags": [
      "Dynamics 365",
      "Power Automate",
      "Microsoft 365",
      "Training"
    ],
    "keywords": [
      "dynamics 365",
      "power automate",
      "real-time marketing",
      "outbound marketing",
      "marketing",
      "training",
      "workflows",
      "automation",
      "microsoft 365",
      "knowledge transfer"
    ],
    "excerpt": "When Microsoft announced in 2024 that it was retiring outbound marketing in favour of real-time marketing, I took on responsibility for getting our key users ready for the switch.",
    "contentHtml": "<p>When Microsoft announced in 2024 that it was retiring outbound marketing in favour of real-time marketing, I took on responsibility for getting our key users ready for the switch.</p>\n<p>The point was to stay ahead of a critical platform change — and just as importantly, to make sure the organisation could own, adjust, and extend the solutions itself afterwards, without leaning on outside help for every adjustment.</p>\n<p><strong>Approach:</strong></p>\n<ul><li>Mapped the workflows and campaigns affected by the move</li><li>Built an internal training plan focused on 1:1 sessions with the super-user in their own subject area</li><li>Did the bulk of the technical setup myself, but built the solution alongside the super-user so the knowledge stayed in the organisation</li><li>Documented processes and configurations for ongoing maintenance</li></ul>\n<p><strong>Results:</strong></p>\n<ul><li>The organisation was prepared</li></ul>"
  },
  {
    "id": "power-apps-power-bi-mal",
    "slug": "power-apps-and-power-bi-department-dashboard-template",
    "title": "Power Apps and Power BI — department dashboard template",
    "role": "Self-initiated learning project",
    "period": "Autumn 2024",
    "year": 2024,
    "featured": true,
    "status": "delivered",
    "sort": 25,
    "tags": [
      "Power Apps",
      "Power BI",
      "SharePoint",
      "Microsoft 365"
    ],
    "keywords": [
      "power apps",
      "power bi",
      "KPI",
      "dashboard",
      "reporting",
      "canvas app",
      "template",
      "sharepoint",
      "galleries",
      "forms",
      "connectors",
      "microsoft 365"
    ],
    "excerpt": "In the autumn of 2024 I spent a fair amount of my own time getting properly into Power Platform — with a particular focus on Power Apps for cases more involved than a basic flow.",
    "contentHtml": "<p>In the autumn of 2024 I spent a fair amount of my own time getting properly into Power Platform — with a particular focus on Power Apps for cases more involved than a basic flow.</p>\n<p>The result was a template application where KPI or key-figure data can be plugged in per department, with embedded Power BI reports and a roll-up landing page for organisation-wide data. SharePoint as the data source.</p>\n<p><strong>Approach:</strong></p>\n<ul><li>Got hands-on with canvas architecture and data-source integration in Power Apps</li><li>Worked through galleries, forms, and connectors in earnest, beyond the simple form-on-list pattern</li><li>Designed the structure so a new department is a new sub-page, not a rebuild</li><li>Embedded Power BI reports directly inside the app</li></ul>\n<p><strong>Results:</strong></p>\n<ul><li>A reusable template for KPI and report visualisation in Power Apps</li><li>A much sharper feel for Power Apps as a</li></ul>"
  }
];
